In [1]:
#important libraries for data manipulation
import pandas as pd
import numpy as np

In [2]:
#actual path of data where your csv file has been saved
train_df = pd.read_csv("/home/adarsh/Hactoberfest/99-ML-Learning-Projects/011/data/twitter_training.csv" , header=None)
test_df = pd.read_csv("/home/adarsh/Hactoberfest/99-ML-Learning-Projects/011/data/twitter_validation.csv" , header=None)

In [3]:
train_df.head()

0            1         2  \
0  2401  Borderlands  Positive   
1  2401  Borderlands  Positive   
2  2401  Borderlands  Positive   
3  2401  Borderlands  Positive   
4  2401  Borderlands  Positive   

                                                   3  
0  im getting on borderlands and i will murder yo...  
1  I am coming to the borders and I will kill you...  
2  im getting on borderlands and i will kill you ...  
3  im coming on borderlands and i will murder you...  
4  im getting on borderlands 2 and i will murder ...

In [4]:
test_df.head()

0          1           2  \
0  3364   Facebook  Irrelevant   
1   352     Amazon     Neutral   
2  8312  Microsoft    Negative   
3  4371      CS-GO    Negative   
4  4433     Google     Neutral   

                                                   3  
0  I mentioned on Facebook that I was struggling ...  
1  BBC News - Amazon boss Jeff Bezos rejects clai...  
2  @Microsoft Why do I pay for WORD when it funct...  
3  CSGO matchmaking is so full of closet hacking,...  
4  Now the President is slapping Americans in the...

In [5]:
train_df.shape

(74682, 4)

In [6]:
test_df.shape

(1000, 4)

In [7]:
train_df.columns = ["id" , "company" , "result" , "sentiment"]
test_df.columns = ["id" , "company" , "result" , "sentiment"]

In [8]:
train_df.sample(1)

id company    result  \
50952  6346    FIFA  Positive   

                                               sentiment  
50952  One of the best things I’ve done this fifa @Ca...

In [9]:
train_df = train_df[["sentiment" , "result"]]
test_df = test_df[["sentiment" , "result"]]

In [10]:
train_df.sample(1)

sentiment   result
43919  Phew just made it.. The season was coming clos...  Neutral

In [11]:
train_df.result.unique()

array(['Positive', 'Neutral', 'Negative', 'Irrelevant'], dtype=object)

In [12]:
replacable_dict = {
    'Positive' : 1,
    'Neutral' : 0,
    'Negative' : 2,
    'Irrelevant' : 3
}

train_df["result"] = train_df["result"].replace(replacable_dict)
test_df["result"] = test_df["result"].replace(replacable_dict)

In [13]:
train_df.head() , test_df.head()

(                                           sentiment  result
 0  im getting on borderlands and i will murder yo...       1
 1  I am coming to the borders and I will kill you...       1
 2  im getting on borderlands and i will kill you ...       1
 3  im coming on borderlands and i will murder you...       1
 4  im getting on borderlands 2 and i will murder ...       1,
                                            sentiment  result
 0  I mentioned on Facebook that I was struggling ...       3
 1  BBC News - Amazon boss Jeff Bezos rejects clai...       0
 2  @Microsoft Why do I pay for WORD when it funct...       2
 3  CSGO matchmaking is so full of closet hacking,...       2
 4  Now the President is slapping Americans in the...       0)

In [14]:
train_df.result.unique()

array([1, 0, 2, 3])

In [15]:
train_df.isnull().sum()

sentiment    686
result         0
dtype: int64

In [16]:
train_df= train_df.dropna()

In [17]:
train_df.isnull().sum()

sentiment    0
result       0
dtype: int64

In [18]:
X_train = train_df["sentiment"][0:50000]
y_train = train_df["result"][0:50000]

X_test = test_df["sentiment"]
y_test = test_df["result"]

In [19]:
X_train[0]

'im getting on borderlands and i will murder you all ,'

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [21]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count , y_train)

MultinomialNB()

In [22]:
X_test[0] , X_test[10]

('I mentioned on Facebook that I was struggling for motivation to go for a run the other day, which has been translated by Tom’s great auntie as ‘Hayley can’t get out of bed’ and told to his grandma, who now thinks I’m a lazy, terrible person 🤣',
 'The professional dota 2 scene is fucking exploding and I completely welcome it.\n\nGet the garbage out.')

In [23]:
sentiments = [
    'I mentioned on Facebook that I was struggling for motivation to go for a run the other day, which has been translated by Tom’s great auntie as ‘Hayley can’t get out of bed’ and told to his grandma, who now thinks I’m a lazy, terrible person 🤣',
    'The professional dota 2 scene is fucking exploding and I completely welcome it.\n\nGet the garbage out.'
]

sentiments_count = v.transform(sentiments)
model.predict(sentiments_count)


array([3, 1])

In [24]:
y_test[0] , y_test[10]

(3, 1)

In [25]:
sentiments_count = v.transform(X_test)
predictions = model.predict(sentiments_count)

In [26]:
predictions

array([3, 0, 2, 2, 0, 2, 1, 1, 1, 2, 1, 1, 2, 0, 2, 1, 1, 2, 1, 2, 1, 0,
       1, 2, 0, 3, 2, 2, 3, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2, 0, 2, 0,
       1, 2, 2, 3, 1, 2, 1, 2, 2, 2, 3, 1, 1, 1, 2, 2, 2, 1, 1, 3, 2, 0,
       2, 1, 1, 2, 1, 1, 2, 1, 1, 3, 1, 3, 2, 0, 0, 1, 1, 0, 1, 0, 2, 3,
       1, 1, 0, 0, 1, 3, 3, 2, 2, 2, 0, 0, 2, 2, 1, 1, 0, 1, 2, 1, 2, 1,
       0, 1, 2, 0, 2, 1, 3, 1, 1, 0, 2, 2, 1, 2, 3, 2, 2, 0, 2, 0, 3, 1,
       0, 1, 1, 3, 0, 0, 0, 3, 2, 0, 0, 3, 1, 0, 1, 0, 1, 3, 2, 2, 3, 0,
       1, 3, 0, 2, 2, 1, 2, 0, 2, 3, 2, 3, 1, 2, 2, 2, 1, 1, 1, 3, 1, 1,
       3, 0, 1, 0, 1, 2, 2, 2, 1, 2, 2, 3, 3, 0, 1, 1, 0, 3, 0, 2, 2, 2,
       2, 1, 0, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 3, 2, 2, 1, 3, 0, 1, 1, 2,
       1, 2, 1, 1, 2, 3, 3, 0, 1, 1, 1, 3, 0, 3, 0, 2, 2, 0, 1, 2, 3, 3,
       1, 1, 3, 3, 0, 1, 0, 2, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 2, 0, 2,
       2, 1, 1, 3, 2, 3, 0, 1, 0, 1, 2, 0, 2, 1, 1, 2, 2, 2, 1, 2, 2, 1,
       0, 0, 2, 1, 2, 1, 3, 1, 0, 0, 1, 2, 0, 2, 3,

In [27]:
model.score(sentiments_count,y_test)

0.752

In [29]:
from sklearn.pipeline import Pipeline

converter = Pipeline([
    ("vectorizer" , CountVectorizer()),
    ("nb" , MultinomialNB())
])

In [31]:
converter.fit(X_train , y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [32]:
converter.predict(X_test)

array([3, 0, 2, 2, 0, 2, 1, 1, 1, 2, 1, 1, 2, 0, 2, 1, 1, 2, 1, 2, 1, 0,
       1, 2, 0, 3, 2, 2, 3, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2, 0, 2, 0,
       1, 2, 2, 3, 1, 2, 1, 2, 2, 2, 3, 1, 1, 1, 2, 2, 2, 1, 1, 3, 2, 0,
       2, 1, 1, 2, 1, 1, 2, 1, 1, 3, 1, 3, 2, 0, 0, 1, 1, 0, 1, 0, 2, 3,
       1, 1, 0, 0, 1, 3, 3, 2, 2, 2, 0, 0, 2, 2, 1, 1, 0, 1, 2, 1, 2, 1,
       0, 1, 2, 0, 2, 1, 3, 1, 1, 0, 2, 2, 1, 2, 3, 2, 2, 0, 2, 0, 3, 1,
       0, 1, 1, 3, 0, 0, 0, 3, 2, 0, 0, 3, 1, 0, 1, 0, 1, 3, 2, 2, 3, 0,
       1, 3, 0, 2, 2, 1, 2, 0, 2, 3, 2, 3, 1, 2, 2, 2, 1, 1, 1, 3, 1, 1,
       3, 0, 1, 0, 1, 2, 2, 2, 1, 2, 2, 3, 3, 0, 1, 1, 0, 3, 0, 2, 2, 2,
       2, 1, 0, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 3, 2, 2, 1, 3, 0, 1, 1, 2,
       1, 2, 1, 1, 2, 3, 3, 0, 1, 1, 1, 3, 0, 3, 0, 2, 2, 0, 1, 2, 3, 3,
       1, 1, 3, 3, 0, 1, 0, 2, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 2, 0, 2,
       2, 1, 1, 3, 2, 3, 0, 1, 0, 1, 2, 0, 2, 1, 1, 2, 2, 2, 1, 2, 2, 1,
       0, 0, 2, 1, 2, 1, 3, 1, 0, 0, 1, 2, 0, 2, 3,

In [34]:
converter.score(X_test , y_test)

0.752